### ISSUE TITLE
Hai , author  can you provide efficientnet_lite1.pth 

### ISSUE THREAD

**Issue by zouzouwei** [dome272/ProjectedGAN-pytorch#1]
because
```python
(hydemo) ynau@ynau-NF5468M5:~/hy/Gan/ProjectedGAN-pytorch$ python efficient_net.py
Traceback (most recent call last):
  File "efficient_net.py", line 257, in <module>
    model.load_state_dict(checkpoint["state_dict"], strict=True)
KeyError: 'state_dict'
```
my efficientnet_lite1.pth is error

my email: hy2056947336@gmail.com

 very  thx y. plz

**Comment by dome272** [comment]
I forgot to provide the links for the efficient net implementation as I see. You can find the original repo here: https://github.com/RangiLyu/EfficientNet-Lite.
They also provide the pretrained models there. Simply download the EfficientNet Lite 1.

**Comment by zouzouwei** [comment]
> I forgot to provide the links for the efficient net implementation as I see. You can find the original repo here: https://github.com/RangiLyu/EfficientNet-Lite. They also provide the pretrained models there. Simply download the EfficientNet Lite 1.

thanks you reply.

i used [https://github.com/RangiLyu/EfficientNet-Lite](url) https://github.com/RangiLyu/EfficientNet-Lite

but, error
``` python
(hydemo) ynau@ynau-NF5468M5:~/hy/Gan/ProjectedGAN-pytorch$ python efficient_net.py
Traceback (most recent call last):
  File "efficient_net.py", line 257, in <module>
    model.load_state_dict(checkpoint["state_dict"], strict=True)
KeyError: 'state_dict'
```

**Comment by dome272** [comment]
The efficient_net.py file is not intended to my run manually. If you want to load the efficient anyways you can refer to this load_checkpoint function https://github.com/dome272/ProjectedGAN-pytorch/blob/b6787b8e4620b6e0c95362e3686bcf35aa696a36/utils.py#L22
